### ISSUE TITLE
Ch08_02Particles/ParticleRenderer.cs - initialize the initial particles on CPU

### ISSUE THREAD

**Issue by CesareSoldani** [spazzarama/Direct3D-Rendering-Cookbook#11]
Hi,

how can I pass thriugh the particle count for firstRun? 

https://github.com/spazzarama/Direct3D-Rendering-Cookbook/blob/7d313ceeee9088c4dca5ac5431a69748ca500f99/Ch08_02Particles/ParticleRenderer.cs#L203

https://github.com/spazzarama/Direct3D-Rendering-Cookbook/blob/7d313ceeee9088c4dca5ac5431a69748ca500f99/Ch08_02Particles/ParticleRenderer.cs#L388

This line seems to overwrite anything I set in the ParticleFrame struct.

Cesare

**Comment by justinstenning** [comment]
@CesareSoldani I'll take a look, however won't be able to get to this until end next week.

**Comment by justinstenning** [comment]
@CesareSoldani the issue is that in the example I have provided I have only given a static value of 0.2f as the energy. This means that after the first loop, all particles expire and a new set is created.

Here is an updated example that will work more sanely for you by setting the energy to a random value between 0 and maxLifeTime:

```csharp
            // Can initialize the initial particles on CPU as long as pass through the count for firstRun
            var particles = new Particle[this.Constants.MaxParticles];
            for (var i = 0; i < particles.Length; i++)
            {
                particles[i].Radius = 0.05f;
                particles[i].Position = random.NextVector3(this.Constants.DomainBoundsMin, this.Constants.DomainBoundsMax);
                particles[i].OldPosition = particles[i].Position;
                particles[i].Energy = random.NextFloat(0, maxLifetime); // THIS IS THE IMPORTANT CHANGE
            }
            
            // Load particles into buffer
            context.UpdateSubresource(particles, particleBuffers[1]);
            context.ComputeShader.SetUnorderedAccessView(0, particleUAVs[0], 0);
            context.ComputeShader.SetUnorderedAccessView(1, particleUAVs[1], maxParticles);

            // Set the starting number of particles to 0
            //context.ComputeShader.SetUnorderedAccessView(0, particleUAVs[0], 0);
            //context.ComputeShader.SetUnorderedAccessView(1, particleUAVs[1], 0);
```
