### ISSUE TITLE
sample for VS2015 & SharpDX 3.0

### ISSUE THREAD

**Issue by PatrickSCLin** [spazzarama/Direct3D-Rendering-Cookbook#2]
Hi, Did you try those sample codes in VS2015 with SharpDX 3.0 ?

I got a lot errors via SharpDX 3.0, even got 2 error via Sharp2.6.3 (Cannot find type System.MarshalByRefObject in module mscorlib.dll)

**Comment by justinstenning** [comment]
I haven't updated to the newer SharpDX version yet. I'll try to sort this in the near future.

**Comment by Gitii** [comment]
I migrated the projects, at least it is now possible to compile them with SharpDX 3.0. Now nuget takes care of all dependencies.
https://github.com/Gitii/Direct3D-Rendering-Cookbook

**Comment by justinstenning** [comment]
Just a note that I've begun working on this in earnest. The VS2015 support is already addressed.

Thanks for your efforts @Gitii. There are a few more compatibility issues I will have to address (Bullet sharp not compatible with SharpDX 3.1.1, and implement a DDS loader).

**Comment by justinstenning** [comment]
SharpDX has been updated to 3.1.1 in commit 8753edbb04a934a2397d90109cf235e043115e93
