### ISSUE TITLE
is possible to offer a very simple SharpDX template for Windows 10 UWP app ?

### ISSUE THREAD

**Issue by PatrickSCLin** [spazzarama/Direct3D-Rendering-Cookbook#3]
I'm new in Visual Studio and C# with Xaml

Can you offer a very simple SharpDX template for Windows 10 UWP Xaml app ?

it would be super helpful for someone who like me :)

is possible just put a SwapChainPanel in MainWindow.xaml, and create device in code and using Swap Chain from SwapChainPanel which just be created.

render a solid background color or simple rect in MainWinodw.cs ?

**Comment by justinstenning** [comment]
Try this project: https://github.com/spazzarama/Direct3D-Rendering-Cookbook/tree/master/Ch11_02HelloSwapChainPanel

You can build all the WinRT apps from D3DRendering.vs2013.WinRT.sln

That works for Windows 8.1 Xaml Windows Store app, I haven't tried on Windows 10 yet, but I imagine it will be fairly close.
