### ISSUE TITLE
Unable to open the Vertex Skinning sample with VS2015

### ISSUE THREAD

**Issue by JakubK** [spazzarama/Direct3D-Rendering-Cookbook#4]
Hi!
Just like in the Title.
I cannot open the Vertex Skinning sample project, the solution is crashing, probably because of the Mesh Targets for visual studio 2013.
When I remove them (the Mesh Render Targets), I can't see my Character on the scene (but the rest is ok). Is there any possibility to open the Vertex Skinning sample with Visual Studio 2015 and without any bugs ?

EDIT: I have found the MeshContentTask files in the Visual Studio 2015's files, then I've added them like in the book, but I still can't see the model (I see only grid).

**Comment by justinstenning** [comment]
I'll take a look for you, last time I checked it was working with VS2015.

**Comment by JakubK** [comment]
Ok, thanks.
I will be waiting for any informations.
The sample with loading a 3D mesh worked for me even without those custom mesh targets.
The sample with Vertex Skinning is showing me only grid...

**Comment by justinstenning** [comment]
@Reaw looking at this now and reproduced the problem. I also had to install the DirectX Developer Runtime for Windows 10 (are you on Windows 10?)

**Comment by JakubK** [comment]
@spazzarama Yes, I'm using the Windows 10.
Can you give me a link for this DirectX Developer Runtime for Windows 10?
I'm googling it but I can't see the perfect result "DirectX Developer Runtime for Windows 10".

**Comment by justinstenning** [comment]
@Reaw the main issue is the MeshContentTask isn't behaving as expected I'll look into it. I'll update the readme with the link, but here it is: https://blogs.msdn.microsoft.com/chuckw/2015/08/05/where-is-the-directx-sdk-2015-edition/

Use the command line in an Admin mode CMD

**Comment by justinstenning** [comment]
Command prompt to install the DirectX Developer Runtime on Windows 10:
`Dism /online /add-capability /capabilityname:Tools.Graphics.DirectX~~~~0.0.1.0`

**Comment by JakubK** [comment]
@spazzarama sadly, nothing has changed after installing this :(.

**Comment by justinstenning** [comment]
@Reaw ok fixed the issue - it is because the MeshContentTask has changed a bit with VS 2015

Attached is a corrected version - I haven't tested if this is backwards compatible with VS2013 yet.
[MeshContentTask.zip](https://github.com/spazzarama/Direct3D-Rendering-Cookbook/files/444646/MeshContentTask.zip)

Replace the MeshContentTask.target in your root solution directory with this one.

**Comment by JakubK** [comment]
@spazzarama That's odd.
After dragging the MeshContentTask from that zip file I cannot run my app because of the following error:

> Error     The "Microsoft.VisualStudio.Graphics.Api.MeshContentTask" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\VsGraphics\Microsoft.VisualStudio.Graphics.Api.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\VsGraphics\Microsoft.VisualStudio.Graphics.Api.dll' or one of its dependencies. Nie można odnaleźć określonego pliku. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. Ch04_01VertexSkinning

**Comment by justinstenning** [comment]
That is odd - compare against what you had before, I haven't changed the path to that file as compared to the checked-in version. (The "UsingTask" node).

**Comment by JakubK** [comment]
I've tried to put those .targets to the next Sample with Animating those bones, there everything compiles fine, but I still can't see the model :( .

**Comment by justinstenning** [comment]
So I replaced the file MeshContentTask.target that is in the same directory as D3DRendering.sln.

The project file Ch04_01VertexSkinning.csproj contains the line `<Import Project="..\MeshContentTask.targets" />` just before the `</Project>` tag.

It now works and creates the "Character.cmo" file in the bin\Debug folder.

**Comment by justinstenning** [comment]
Can you confirm where the Microsoft.VisualStudio.Graphics.Api.dll is located on your machine? Perhaps your install location is different.

**Comment by JakubK** [comment]
@spazzarama Ok, I've replaced the path in this .targets file on the correct one.
Now when I will run my app I'm getting FileLoadException.
When I will change the the Mesh's initialization line to the following:

> var loadedMesh = Common.Mesh.LoadFromFile("Character.cmo");

Then I will again get the Scene with the grid, and nothing else

**Comment by justinstenning** [comment]
@reaw you shouldn't need to change anything there. Can you check that the character.cmo file is in the bin\Debug directory?

**Comment by JakubK** [comment]
@spazzarama Yes it is.

**Comment by justinstenning** [comment]
@Reaw ok well the initial problem is solved (MeshContentTask not creating the .cmo file).

You may need to step through and find out why you get the FileLoadException. I presume that is coming out in the debug output (as the exception is being swallowed in my version). If it is the File.OpenRead line then just adjust the path accordingly perhaps - or maybe your application is not running from within the same directory (VS sometimes does that with debug mode).

**Comment by JakubK** [comment]
@spazzarama  Ok thanks I will try to find this bug.

**Comment by justinstenning** [comment]
ecb08f1 includes updated MeshContentTask.targets
