### ISSUE TITLE
How to compile with VS2017 (MeshContentTask.targets)

### ISSUE THREAD

**Issue by ziriax** [spazzarama/Direct3D-Rendering-Cookbook#8]
This is because the MeshContentTask.targets is referring to the wrong VS installation folder.

The following should fix that:

```
 <UsingTask TaskName="Microsoft.VisualStudio.Graphics.Api.MeshContentTask" AssemblyFile="$(VSInstallDir)\Common7\IDE\Extensions\Microsoft\VsGraphics\Microsoft.VisualStudio.Graphics.Api.dll" />
```

**Comment by justinstenning** [comment]
Unfortunately $(VSInstallDir) is not set for me on VS2015 or VS2017.

If you have to change the location to suit your VS installation make sure to do so in the following files:
 .\ImageContentTask.targets
 .\MeshContentTask.targets
 .\ShaderGraphContentTask.targets

**Comment by ziriax** [comment]
I see. What about ’$(DevEnvDir)’?

**Comment by athompson887** [comment]
I have been having a similar issue but following the above good advice I have edited the path in the MeshContentTask and the cmo file is being built.  My problem now is the associated model texture isn't being made.  I noticed that Justin has supplied precompiled dds files and cmo files.  Whilst these work  I really need to be able to build my own to complete my project.   Any help and advice would be appreciated.

**Comment by cfeied** [comment]
I encountered the same issue, and VSInstallDir also is not defined for me in VS2017. What worked was to substitute VsInstallRoot.

The revised (working) change to MeshContentTask.targets is to replace the existing line 

`< UsingTask TaskName="Microsoft.VisualStudio.Graphics.Api.MeshContentTask" AssemblyFile="C:\Program Files (x86)\Microsoft Visual Studio $(VisualStudioVersion)\Common7\IDE\Extensions\Microsoft\VsGraphics\Microsoft.VisualStudio.Graphics.Api.dll" /> `

with the new line:

`<UsingTask TaskName="Microsoft.VisualStudio.Graphics.Api.MeshContentTask" AssemblyFile="$(VSInstallRoot)\Common7\IDE\Extensions\Microsoft\VsGraphics\Microsoft.VisualStudio.Graphics.Api.dll" />`
